import { StyleSheet } from 'react-native';
import { brandColors, colors, radius, space, type } from '../../theme';
export const challengeStyles = StyleSheet.create({
  page: { flex: 1, backgroundColor: '#EFF8FE' },
  content: { padding: space.xl, gap: space.lg, maxWidth: 640, width: '100%', alignSelf: 'center' },
  stack: { gap: space.md }, compact: { gap: space.sm },
  title: { ...type.title, fontSize: 26, lineHeight: 32, color: brandColors.navy },
  heading: { ...type.heading, color: brandColors.navy }, body: type.body, caption: type.caption,
  chip: { ...type.caption, alignSelf: 'flex-start', backgroundColor: '#E3F0FF', paddingVertical: 4, paddingHorizontal: 12, color: colors.blue, borderRadius: radius.pill, fontWeight: '700' },
  card: { backgroundColor: colors.white, borderRadius: radius.card, borderWidth: 1, borderColor: colors.border, padding: space.lg, gap: space.md },
  includes: { gap: space.md }, tile: { flexDirection: 'row', alignItems: 'flex-start', gap: space.md },
  tileIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.pale, alignItems: 'center', justifyContent: 'center' },
  tileText: { flex: 1, gap: space.xs }, tileTitle: { ...type.body, color: colors.ink, fontWeight: '700' },
  chatRow: { flexDirection: 'row', alignItems: 'flex-start', gap: space.sm },
  avatar: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#DCEBFF', alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: colors.blue, fontWeight: '700', fontSize: 16 },
  bubble: { flexShrink: 1, borderRadius: radius.hero, backgroundColor: colors.white, padding: space.md, gap: space.xs, borderWidth: 1, borderColor: colors.border },
  reply: { alignSelf: 'flex-end', marginLeft: 40, backgroundColor: '#E8F2FF', borderColor: '#C6DFFF' },
  speaker: { ...type.caption, fontWeight: '600' }, chatText: { ...type.body, fontSize: 17, lineHeight: 24, color: colors.ink },
  option: { flexDirection: 'row', alignItems: 'center', gap: space.md, borderWidth: 1.5, borderColor: colors.border, borderRadius: radius.card, minHeight: 48, padding: space.md, backgroundColor: colors.white },
  optionText: { flex: 1, color: colors.ink, fontWeight: '500', fontSize: 17, lineHeight: 24 },
  optionTextSelected: { color: colors.blue, fontWeight: '700' },
  radio: { width: 20, height: 20, borderWidth: 1.5, borderColor: colors.gray, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  radioSelected: { borderColor: colors.blue }, radioDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: colors.blue },
  selected: { backgroundColor: '#E8F2FF', borderColor: colors.blue },
  grid: { alignItems: 'center', paddingVertical: space.xs },
  cell: { borderWidth: 1, borderColor: '#97BEE8', borderRadius: 4, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.white },
  letter: { color: colors.ink, fontWeight: '700' },
  cellNumber: { position: 'absolute', left: 2, top: 0, color: '#42638B' },
  input: { minHeight: 48, borderWidth: 1.5, borderColor: colors.blue, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 8, color: colors.ink, fontSize: 19, backgroundColor: colors.white, letterSpacing: 2 },
  clueColumns: { flexDirection: 'row', flexWrap: 'wrap', gap: space.md },
  clueColumn: { flex: 1, gap: space.xs },
  clueHeading: { ...type.body, color: colors.ink, fontWeight: '700' },
  clue: { minHeight: 44, paddingVertical: 8, paddingHorizontal: 8, borderRadius: 10, borderWidth: 1, borderColor: 'transparent', justifyContent: 'center' },
  clueSelected: { color: colors.blue, fontWeight: '600' },
  score: { alignItems: 'center', gap: space.md }, scoreNumber: { color: colors.ink, fontSize: 34, fontWeight: '800' },
});
